name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: wallets.tex
          latexmk_use_lualatex: true
      - uses: actions/upload-artifact@v2
        with:
          path: wallets.pdf
